// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnssqkwnehtmuzlszvno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Induc3Nxa3duZWh0bXV6bHN6dm5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNDMyMDQsImV4cCI6MjA2MjgxOTIwNH0.S6QuPuyZhUWbuOB2rjaiVcfi8zUC7mCEaxHAOGOeb-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);